name: e2e UI tests in docker

on: 
  push:
    branches:
      - "ga-docker"

jobs:
  chrome:
    runs-on: ubuntu-latest
    name: trigger in chrome
    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v5
        with:
          browser: chrome
          spec: cypress/e2e/custom_scenarios/newborn.cy.js